name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build and Publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/quintesse/vertx-configmap-example/vertx-configmap-example
        username: quintesse
        password: ${{ secrets.GITHUB_TOKEN }}
