name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build container image
      run: |
        SHORTSHA=$(echo "${{ github.sha }}" | cut -c-7)
        docker build -t docker.pkg.github.com/quintesse/vertx-configmap-example/vertx-configmap-example:${SHORTSHA} .
        docker tag docker.pkg.github.com/quintesse/vertx-configmap-example/vertx-configmap-example:${SHORTSHA} docker.pkg.github.com/quintesse/vertx-configmap-example/vertx-configmap-example:latest
        echo "::set-env SHORTSHA=${SHORTSHA}"

    - name: Push image to GPR
      if: success()
      run: |
        docker login docker.pkg.github.com -u ${{ github.actor }} -p "${GITHUB_TOKEN}"
        docker push docker.pkg.github.com/quintesse/vertx-configmap-example/vertx-configmap-example:${SHORTSHA}
        docker push docker.pkg.github.com/quintesse/vertx-configmap-example/vertx-configmap-example:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
